version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=hmw_user
      - POSTGRES_PASSWORD=hmw_password
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=hmwdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: